server:
  port: 8090

# QQ Bot Configuration
bot:
  qq: xxx
  qqName: xxx
  password: xxx
  napcatqq:
    enabled: true
    endpoint: /napcatqq/message
    url: xxx
    accessToken: xxxxx
  listener:
    group: "xxx,xxx"
    msgBegin: "提问,/,@,成语"


# DeepSeek API Configuration
deepseek:
  api:
    url: https://api.deepseek.com/chat/completions
    key: xxxxxx
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: xxxxx
        modelName: qwen3-max
      streaming-chat-model:
        api-key: XXXXX
        modelName: qwen3-max
      embedding-model: #向量模型
        api-key: xxxxx
qw:
  api:
    url: https://qw.deepseek.com/api/v1/chat/completions
    key: xxxxxx
# MySQL Database Configuration
spring:
  profiles:
    active: dev  # 默认使用开发环境配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:xxx/xxx?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: xxx
    password: xxx
    hikari:
      pool-name: HikariCP-Pool
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      # 批量操作优化参数
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
        useLocalSessionState: true

# MyBatis-Plus Configuration
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.hudi.qqboot.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto